#!/usr/bin/env bash

set -euo pipefail

CONFIG="$1"
OUTPUT_DIRECTORY="$2"

FIXED_CONFIG="$OUTPUT_DIRECTORY/config.json"
ALL_BACKUPED_FILES="$OUTPUT_DIRECTORY/all-backuped-files"
ALL_FILES="$OUTPUT_DIRECTORY/all-files"

function log() {
    echo "$1" > /dev/stderr
}

mkdir -p "$OUTPUT_DIRECTORY"

log "Removing restic-binary"
yq 'del(.global."restic-binary")' < "$CONFIG" > "$FIXED_CONFIG"

rm -f "$ALL_BACKUPED_FILES"

for PROFILE_NAME in $(yq -r 'to_entries | map(select(.value.inherit == "common") | .key) | .[]' "$FIXED_CONFIG" | sort); do
    log "Collecting files backed up by $PROFILE_NAME"
    resticprofile -c "$FIXED_CONFIG" --name "$PROFILE_NAME" unlock
    resticprofile -c "$FIXED_CONFIG" --name "$PROFILE_NAME" backup --dry-run --verbose=2 --json | grep message_type > "$OUTPUT_DIRECTORY/$PROFILE_NAME.log.json" || true
    cat "$OUTPUT_DIRECTORY/$PROFILE_NAME.log.json" | jq -r 'select(.action == "new").item' >> "$ALL_BACKUPED_FILES"
done

ROOT_PATHS="$(find / -mindepth 1 -maxdepth 1 | grep -vE '/nix|/sys|/proc|/dev|/bin|/usr|/tmp|/lib|/lib64|/mnt|/run' | xargs echo)"

log "Collecting all files in $ROOT_PATHS"
find $ROOT_PATHS -type f > "$ALL_FILES"

log "Computing missing files"
diffset "$ALL_FILES" "$ALL_BACKUPED_FILES" > "$OUTPUT_DIRECTORY/non-backuped-files"

log "Computing missing files not explicitly excluded"
FILTER=$(yq -r '
to_entries
| map(select(.value.inherit == "common")) as $configurations
| ($configurations | map(.value.backup.exclude | select(. != null)) | add | map(gsub("\\*"; ".*"))) as $excluded
| ($configurations | map(.value.backup.source) | add) as $sources
| $excluded - $sources | .[]
' < "$FIXED_CONFIG" | paste -s -d '|' -)

for EXCLUDE_FILE in $(yq -r '.common.backup."exclude-if-present" | .[]' < "$FIXED_CONFIG"); do
    NEW_FILTER=$(grep "$EXCLUDE_FILE" "$OUTPUT_DIRECTORY"/all-files | sed 's|/'"$EXCLUDE_FILE"'$||' | paste -s -d '|' -)
    FILTER="$FILTER|$NEW_FILTER"
done

grep -avE "^($FILTER)" "$OUTPUT_DIRECTORY"/non-backuped-files > "$OUTPUT_DIRECTORY/implicitly-non-backuped-files"

for LOG in "$OUTPUT_DIRECTORY"/*.log.json; do
    echo "$LOG: $(( $(tail -n2 "$LOG"  | head -n1 | jq '.data_added_packed') / (1024 * 1024 * 1024))) GB"
done

log "All done"
