from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import jsonschema
import yaml


# Config keys that map to a different restic flag name.
KEY_ALIASES: dict[str, str] = {
    "repository": "repo",
}

# Sub-sections of a profile that are command-specific: they override base
# settings only when that command is being invoked. Anything not in this set
# is treated as a top-level setting common to all commands.
COMMAND_SECTIONS = frozenset({
    "backup", "unlock", "snapshots", "restore", "mount",
    "check", "forget", "prune", "init", "find", "ls",
    "stats", "tag", "diff", "copy", "rebuild-index", "cat",
    "dump", "key", "list", "migrate", "recover", "repair",
})


_PROFILE_PROPERTIES: dict[str, dict[str, Any]] = {
    "inherit": {"type": "string"},
    "repository": {"type": "string"},  # alias for restic's --repo
    "env": {
        "type": "object",
        "additionalProperties": {"type": ["string", "number", "boolean"]},
    },
}

# Top-level `rip:` section: knobs that describe rip's behavior (how it
# orchestrates) rather than a particular restic invocation. Same set is
# rejected if it appears inside a profile.
_RIP_PROPERTIES: dict[str, dict[str, Any]] = {
    "added-size-limit": {"type": ["string", "integer"]},
    "skip-on-battery": {"type": "boolean"},
    "wifi-whitelist": {"type": "array", "items": {"type": "string"}},
    "wifi-blacklist": {"type": "array", "items": {"type": "string"}},
}


def _load_restic_flags() -> dict[str, dict[str, Any]]:
    """Restic flag types generated by scripts/generate_restic_flags.py.

    When the snapshot is absent (e.g. installed without ever running the
    generator) the profile schema falls back to permissive mode and only
    rip-specific keys / command sections are typed strictly.
    """
    path = Path(__file__).parent / "restic_flags.json"
    if not path.exists():
        return {}
    flags: dict[str, dict[str, Any]] = json.loads(path.read_text()).get("flags", {})
    return flags


_RESTIC_FLAGS = _load_restic_flags()


def _build_profile_schema() -> dict[str, Any]:
    properties: dict[str, dict[str, Any]] = {**_RESTIC_FLAGS, **_PROFILE_PROPERTIES}
    # Command sub-sections (backup:, forget:, ...) stay permissive — each
    # holds command-local restic flags we don't enumerate per-command.
    for section in COMMAND_SECTIONS:
        properties[section] = {"type": "object"}
    return {
        "type": "object",
        "additionalProperties": not _RESTIC_FLAGS,  # permissive only if snapshot absent
        "properties": properties,
    }


CONFIG_SCHEMA: dict[str, Any] = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "additionalProperties": False,
    "properties": {
        # Sections
        "profiles": {
            "type": "object",
            "additionalProperties": {"$ref": "#/$defs/profile"},
        },
        "fix-homes": {
            "type": "object",
            "additionalProperties": {"$ref": "#/$defs/fixHomeUser"},
        },
        # Top-level rip knobs (these are rejected inside profiles).
        "log-path": {"type": "string"},
        **_RIP_PROPERTIES,
    },
    "$defs": {
        "profile": _build_profile_schema(),
        "fixHomeUser": {
            "type": "object",
            "additionalProperties": {
                "type": "array",
                "items": {"type": "string"},
            },
        },
    },
}


def rip_settings(config: dict[str, Any]) -> dict[str, Any]:
    """Return the rip-only knobs that live at the top level of the config."""
    return {k: v for k, v in config.items() if k in _RIP_PROPERTIES}

_validator = jsonschema.Draft202012Validator(CONFIG_SCHEMA)


class ConfigError(Exception):
    pass


def load_config(path: str) -> dict[str, Any]:
    try:
        with open(path) as f:
            config = yaml.safe_load(f) or {}
    except FileNotFoundError as e:
        raise ConfigError(f"Config file not found: {path}") from e
    except yaml.YAMLError as e:
        raise ConfigError(f"Could not parse {path} as YAML: {e}") from e

    try:
        _validator.validate(config)
    except jsonschema.ValidationError as e:
        location = "/".join(str(p) for p in e.absolute_path) or "<root>"
        raise ConfigError(f"{path}: schema error at {location}: {e.message}") from e

    return config


def children_of(config: dict[str, Any], parent: str) -> list[str]:
    """Names of profiles that directly inherit from `parent`, sorted."""
    return sorted(
        name
        for name, settings in config.get("profiles", {}).items()
        if isinstance(settings, dict) and settings.get("inherit") == parent
    )


def resolve(config: dict[str, Any], name: str, command: str) -> tuple[dict[str, Any], dict[str, Any]]:
    """Return (settings, env) for `command` under profile `name`, applying inheritance."""
    profiles = config.get("profiles", {})
    if name not in profiles:
        raise KeyError(f"Profile {name!r} not found")

    chain: list[dict[str, Any]] = []
    seen: set[str] = set()
    current: str | None = name
    while current:
        if current in seen:
            raise ValueError(f"Inheritance cycle involving {current!r}")
        seen.add(current)
        chain.append(profiles[current])
        current = chain[-1].get("inherit")

    merged: dict[str, Any] = {}
    for profile in reversed(chain):
        for key, value in profile.items():
            if key == "inherit":
                continue
            if isinstance(value, dict):
                if key == "env":
                    merged.setdefault("env", {}).update(value)
                elif key in COMMAND_SECTIONS:
                    merged.setdefault(key, {}).update(value)
                # else: stray sub-section (e.g. resticprofile's `retention:`);
                # drop it — translating a dict to a restic flag is never right.
                continue
            merged[key] = value

    command_settings = merged.pop(command, {})
    for section in COMMAND_SECTIONS:
        merged.pop(section, None)
    merged.update(command_settings)

    env = merged.pop("env", {})
    return merged, env


def has_section(config: dict[str, Any], name: str, section: str) -> bool:
    """True if profile `name` (or any ancestor) defines a non-empty `section`."""
    profiles = config.get("profiles", {})
    seen: set[str] = set()
    current: str | None = name
    while current and current not in seen:
        seen.add(current)
        profile = profiles.get(current, {})
        if profile.get(section):
            return True
        current = profile.get("inherit")
    return False


def to_argv(settings: dict[str, Any], command: str) -> tuple[list[str], list[str]]:
    """Translate `settings` (from `resolve`) to flag args and positional args."""
    settings = dict(settings)
    sources = settings.pop("source", []) if command == "backup" else []
    if isinstance(sources, str):
        sources = [sources]

    flags: list[str] = []
    for key, value in settings.items():
        flag = "--" + KEY_ALIASES.get(key, key)
        if isinstance(value, bool):
            if value:
                flags.append(flag)
        elif isinstance(value, list):
            for item in value:
                flags.extend([flag, str(item)])
        else:
            flags.extend([flag, str(value)])

    return flags, [str(s) for s in sources]


def build_command(
    config: dict[str, Any], name: str, command: str,
) -> tuple[list[str], dict[str, str]]:
    """Return (argv, env) ready to spawn restic for profile `name` running `command`.

    argv is ["restic", command, *flags, *positionals]; env is the profile's
    env block (e.g. RESTIC_PASSWORD), stringified."""
    settings, env = resolve(config, name, command)
    flags, positionals = to_argv(settings, command)
    return ["restic", command, *flags, *positionals], {k: str(v) for k, v in env.items()}
